<x-layout>
    <div class="mx-auto max-w-(--breakpoint-2xl) space-y-6 p-4 pb-20 md:p-6 md:pb-6">
        <header class="flex flex-col gap-4 border-b border-gray-200 pb-6 sm:flex-row sm:justify-between dark:border-gray-800">
            <div><p class="text-theme-xs font-medium uppercase text-gray-500">{{ $application->reference }}</p><h1 class="mt-1 text-xl font-semibold text-gray-900 dark:text-white/90">{{ $application->first_name }} {{ $application->last_name }}</h1><p class="mt-1 text-theme-sm text-gray-500">{{ $application->job->title }} at {{ $application->job->company }}</p></div>
            <a href="{{ route('employer.Applied-Candidates') }}" class="inline-flex h-10 items-center justify-center rounded-lg border border-gray-300 px-4 text-theme-sm font-medium text-gray-700 dark:border-gray-700 dark:text-gray-300">Back to pipeline</a>
        </header>
        @if (session('success'))<div class="rounded-lg border border-success-200 bg-success-50 px-4 py-3 text-theme-sm text-success-700" role="status">{{ session('success') }}</div>@endif
        @if ($errors->any())<div class="rounded-lg border border-error-200 bg-error-50 px-4 py-3 text-theme-sm text-error-700" role="alert">{{ $errors->first() }}</div>@endif
        <div class="grid gap-6 xl:grid-cols-12">
            <main class="space-y-6 xl:col-span-8">
                <section class="overflow-hidden rounded-xl border border-gray-200 bg-white dark:border-gray-800 dark:bg-white/[0.03]"><div class="border-b border-gray-100 px-5 py-4 dark:border-gray-800"><h2 class="text-lg font-semibold text-gray-900 dark:text-white/90">Submitted documents</h2><p class="mt-1 text-theme-sm text-gray-500">Files are retained as application evidence.</p></div><div class="divide-y divide-gray-100 dark:divide-gray-800">@forelse($application->documents as $document)<div class="flex items-center justify-between gap-4 px-5 py-4"><div><p class="text-theme-sm font-medium text-gray-800 dark:text-white/90">{{ $document->document_name }}</p><p class="text-theme-xs text-gray-500">{{ $document->original_name }}</p></div><a href="{{ $document->canPreviewInline() ? $document->previewUrl() : $document->downloadUrl() }}" target="_blank" rel="noopener" class="text-theme-sm font-medium text-brand-500">View file</a></div>@empty<div class="px-5 py-8 text-theme-sm text-gray-500">No documents submitted.</div>@endforelse</div></section>
                <section class="rounded-xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]"><h2 class="text-lg font-semibold text-gray-900 dark:text-white/90">Pipeline history</h2><ol class="mt-4 divide-y divide-gray-100 dark:divide-gray-800">@forelse($application->statusHistories->sortByDesc('created_at') as $history)<li class="py-3"><div class="flex justify-between gap-4"><span class="font-medium text-gray-800 dark:text-white/90">{{ $history->to_status->label() }}</span><time class="text-theme-xs text-gray-500">{{ $history->created_at->format('M d, Y g:i A') }}</time></div>@if($history->remarks)<p class="mt-1 text-theme-sm text-gray-500">{{ $history->remarks }}</p>@endif</li>@empty<li class="py-3 text-theme-sm text-gray-500">No stage changes yet.</li>@endforelse</ol></section>
            </main>
            <aside class="space-y-6 xl:col-span-4">
                <section class="rounded-xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]"><h2 class="text-lg font-semibold text-gray-900 dark:text-white/90">Candidate pipeline</h2><div class="mt-3"><span class="inline-flex rounded-full px-2.5 py-1 text-theme-xs font-medium {{ $application->status->badgeClass() }}">{{ $application->status->label() }}</span></div>@if($application->status->isTerminal())<p class="mt-4 text-theme-sm text-gray-500">This candidate is in a terminal stage.</p>@else<form action="{{ route('employer.applications.pipeline.move', $application) }}" method="POST" class="mt-5 space-y-4">@csrf @method('PATCH')<div><label for="stage" class="mb-1.5 block text-theme-sm font-medium text-gray-700 dark:text-gray-300">Move to</label><select id="stage" name="stage" required class="h-11 w-full rounded-lg border border-gray-300 bg-white px-3 text-theme-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"><option value="">Select stage</option>@foreach($application->status->allowedNextStages() as $stage)<option value="{{ $stage->value }}">{{ $stage->label() }}</option>@endforeach</select></div><div><label for="remarks" class="mb-1.5 block text-theme-sm font-medium text-gray-700 dark:text-gray-300">Note <span class="font-normal text-gray-500">Optional</span></label><textarea id="remarks" name="remarks" rows="4" maxlength="2000" class="w-full rounded-lg border border-gray-300 px-3 py-2 text-theme-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90">{{ old('remarks') }}</textarea></div><button class="inline-flex h-11 w-full items-center justify-center rounded-lg bg-brand-500 text-theme-sm font-medium text-white hover:bg-brand-600">Update candidate stage</button></form>@endif</section>
                <section class="rounded-xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]"><h2 class="text-lg font-semibold text-gray-900 dark:text-white/90">Applicant details</h2><dl class="mt-4 space-y-3 text-theme-sm"><div><dt class="text-gray-500">Email</dt><dd class="font-medium text-gray-800 dark:text-white/90">{{ $application->email }}</dd></div><div><dt class="text-gray-500">Phone</dt><dd class="font-medium text-gray-800 dark:text-white/90">{{ $application->phone }}</dd></div><div><dt class="text-gray-500">Submitted</dt><dd class="font-medium text-gray-800 dark:text-white/90">{{ $application->submitted_at->format('M d, Y g:i A') }}</dd></div></dl></section>
            </aside>
        </div>
    </div>
</x-layout>
